language: python
python:
- "2.7"
- "3.2"
- "3.3"
# command to install dependencies
install:
   - "pip install nose pep8 pylint coverage --use-mirrors"
# command to run tests
script:
   - ./run_pythontest.py
